import { FileText, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Panel, PageHeader, SectionTitle } from "../Primitives";

const docs = [
  { name: "Monthly MIS Pack — October 2025", type: "PDF", size: "4.2 MB", date: "01 Nov" },
  { name: "Detailed P&L FY26 YTD", type: "Excel", size: "1.8 MB", date: "01 Nov" },
  { name: "Balance Sheet Movement", type: "PDF", size: "2.1 MB", date: "01 Nov" },
  { name: "Debtor Ageing Report", type: "Excel", size: "740 KB", date: "31 Oct" },
  { name: "Creditor Ageing Report", type: "Excel", size: "612 KB", date: "31 Oct" },
  { name: "Trial Balance — Oct", type: "PDF", size: "1.4 MB", date: "31 Oct" },
  { name: "Variance Report — Budget vs Actual", type: "Excel", size: "920 KB", date: "31 Oct" },
  { name: "GST Reconciliation Pack", type: "PDF", size: "3.2 MB", date: "28 Oct" },
  { name: "Cash Flow Statement", type: "PDF", size: "1.1 MB", date: "31 Oct" },
];

export function Documents() {
  return (
    <div className="space-y-8">
      <PageHeader
        title="Documents & Downloads"
        subtitle="All financial reports, statements and supporting documents in one place."
      />
      <Panel>
        <SectionTitle title="Latest Reports" subtitle="Auto-generated by your finance team" />
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {docs.map(d => (
            <div key={d.name} className="group rounded-lg border border-border bg-card p-4 flex items-start gap-3 hover:shadow-elegant transition-all hover:border-gold/40">
              <div className="size-10 rounded-md bg-gradient-gold-soft border border-gold/30 flex items-center justify-center shrink-0">
                <FileText className="size-5 text-foreground" />
              </div>
              <div className="flex-1 min-w-0">
                <div className="text-sm font-medium leading-snug">{d.name}</div>
                <div className="text-[11px] text-muted-foreground mt-1">
                  {d.type} · {d.size} · {d.date}
                </div>
              </div>
              <Button size="icon" variant="ghost" className="size-8 opacity-60 group-hover:opacity-100">
                <Download className="size-4" />
              </Button>
            </div>
          ))}
        </div>
      </Panel>
    </div>
  );
}
